---
title: "LAB 7 GitHUB Assignment"
author: "Carter Davey"
format: html
editor: visual
---

```{r}
library(readxl)
library(sf)
library(tidyverse)
library(mapview)
library(bcmaps)
library(tidyverse)
library(terra)
library(bcdata)
library(dplyr)
library(units)


View(available_layers())
Hist_Inc_Fire<- ecoregions()
mapview(Hist_Inc_Fire)

park_search_results <- bcdc_search("BC Parks Ecological Reserves Protected Areas")
View(park_search_results)

protected_areas <- bcdc_get_data(record = "1130248f-f1a3-4956-8b2e-38d29d3e4af7")
view(protected_areas)

LacDuBois <- protected_areas %>%
  filter(PROTECTED_LANDS_NAME == "LAC DU BOIS GRASSLANDS PROTECTED AREA")
mapview(LacDuBois)



Hist_fire_search_results <- bcdc_get_data(record = "e2dadc60-292f-4d98-b42b-56ca9e4fe694")
View(Hist_fire_search_results)




Hist_fire_locations <- st_as_sf(Hist_fire_search_results)

LacDuBois <- st_transform(LacDuBois, st_crs(Hist_fire_locations))

Hist_Fire_In_LacDuBois <- st_intersection(Hist_fire_locations, LacDuBois)

mapview(Hist_Fire_In_LacDuBois)
view(Hist_Fire_In_LacDuBois)



```

```{r}
## •	Summarise this dataset to show how many fires occurred by fire year
fire_year_counts <- Hist_Fire_In_LacDuBois %>%
  select(FIRE_YEAR) %>%
  count(FIRE_YEAR)



view(fire_year_counts)
print(fire_year_counts, number_of_fires)
```

```{r}
##•	Create another data summary that shows the overall breakdown of fire cause in the Lac Du Bois Grasslands Protected Area.

fire_cause <- Hist_Fire_In_LacDuBois %>%
  select(FIRE_CAUSE) %>%
  count(FIRE_CAUSE)


view(fire_cause)
print(fire_cause, fire_cause)
```

```{r}
##•	Generate a mapview of the fire points with colors to illustrate the fire cause.


mapview(Hist_Fire_In_LacDuBois, zcol = "FIRE_CAUSE", col.regions = rainbow(length(unique(Hist_Fire_In_LacDuBois$FIRE_CAUSE))))


```

```{r}

library(ggplot2)

MEAN_FIRES <- Hist_Fire_In_LacDuBois %>%
  group_by(FIRE_CAUSE, FIRE_YEAR) %>%
  summarise(mean_fires = n() / length(unique(FIRE_YEAR))) %>%
  group_by(FIRE_CAUSE) %>%
  summarise(mean_fires = mean(mean_fires))


ggplot(mean_fires, aes(x = FIRE_CAUSE, y = mean_fires, fill = FIRE_CAUSE)) +
  geom_boxplot() +
  labs(x = "Fire Cause", y = "Mean Number of Fires per Year") +
  theme_minimal()


```
